# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-{{cookiecutter.plugin_name}}:
  variables:
    PLUGIN_NAME: vdk-{{cookiecutter.plugin_name}}
  extends: .build-plugin

build-py37-vdk-{{cookiecutter.plugin_name}}:
  extends: .build-vdk-{{cookiecutter.plugin_name}}
  image: "python:3.7"


build-py38-vdk-{{cookiecutter.plugin_name}}:
  extends: .build-vdk-{{cookiecutter.plugin_name}}
  image: "python:3.8"

build-py39-vdk-{{cookiecutter.plugin_name}}:
  extends: .build-vdk-{{cookiecutter.plugin_name}}
  image: "python:3.9"

build-py310-vdk-{{cookiecutter.plugin_name}}:
  extends: .build-vdk-{{cookiecutter.plugin_name}}
  image: "python:3.10"

release-vdk-{{cookiecutter.plugin_name}}:
  variables:
    PLUGIN_NAME: vdk-{{cookiecutter.plugin_name}}
  extends: .release-plugin
